#!/bin/sh

image="$1"
if [ -z "$image" ] ; then
  image="ecmwf/ecpoint-pycal:latest"
fi

exec docker run \
     --rm \
     --read-only \
     --user $(id -u):$(id -g) \
     -e DISPLAY=$DISPLAY \
     -e HOME=$HOME \
     -e http_proxy=$http_proxy \
     -e https_proxy=$https_proxy \
     -e ftp_proxy=$ftp_proxy \
     -e no_proxy=$no_proxy \
     -v /home:/home \
     -v /hugetmp:/hugetmp \
     -v /perm:/perm \
     -v /scratch:/scratch \
     -v /tmp:/tmp \
     -v /var/tmp:/var/tmp \
     $image
